name: node test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install both dependencies 
      run: |
        npm install
    - name: check if build is broken through node
      run: |
        node index.js
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
